# UI
OF_SCREEN_H := 2400
OF_STATUS_H := 108
OF_STATUS_INDENT_LEFT := 64
OF_STATUS_INDENT_RIGHT := 64
OF_HIDE_NOTCH := 1
OF_CLOCK_POS := 1
OF_USE_GREEN_LED := 0
OF_ALLOW_DISABLE_NAVBAR := 0
OF_USE_LOCKSCREEN_BUTTON := 1

# Timezone
OF_DEFAULT_TIMEZONE := CET-1CEST,M3.5.0,M10.5.0/3

# OrangeFox
FOX_VIRTUAL_AB_DEVICE := 1
FOX_RECOVERY_SYSTEM_PARTITION := /dev/block/mapper/system
FOX_RECOVERY_VENDOR_PARTITION := /dev/block/mapper/vendor
OF_QUICK_BACKUP_LIST := /boot;/data;/dtbo;

# disable the flashlight
OF_FLASHLIGHT_ENABLE := 0

# battery percent
OF_USE_LEGACY_BATTERY_SERVICES := 1

# Maintainer
FOX_BUILD_TYPE := Stable
OF_MAINTAINER := @medusa659||YamaMoto
FOX_MAINTAINER_PATCH_VERSION := 1
